### ISSUE TITLE
자동 테스트 CI 환경 구축

### ISSUE THREAD

**Issue by hanbin8269** [Doran-Doran-development/DoranDoran-Server-2#7]
- github action 으로 작성
- `master`, `develop`에 푸시하면 작동하도록
- `python manage.py test` 명령어로 동작하도록

**Comment by icefirebear** [comment]
> * `master`, `develop`에 푸시하면 작동하도록

PR 보냈을 때도 작동되게 하면 좋을 것 같습니다.

**Comment by hanbin8269** [comment]
좋습니다

**Comment by hanbin8269** [comment]
지금 있는 오류 해결하고 따로 환경변수 설정하는게 더 있을겁니다... 수정 부탁드립니다

**Comment by icefirebear** [comment]
> 지금 있는 오류 해결하고 따로 환경변수 설정하는게 더 있을겁니다... 수정 부탁드립니다
네 확인하고 수정완료 했습니다👍

**Comment by hanbin8269** [comment]
master 브랜치에서 제거하고 따로 브랜치 만들어서 처리했습니다
